language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install -r dev-requirements.in
script:
  - tox
  - flake8 --ignore=E221 challengeauth.py test_challengeauth.py
